### ISSUE TITLE
Importing scripts to backpack puts scripts at the end of the backpack, not the start

### ISSUE THREAD

**Issue by liam4** [tjvr/scratchblocks#184] opened 2016-07-08 18:16 UTC
![Picture](https://cloud.githubusercontent.com/assets/9948030/16697176/d1365d40-451e-11e6-8fc6-3df43a705b1c.png)

On the far right are the newly imported using scratchblocks scripts. Everything else is from, like, 2013.

**Comment by tjvr** [comment] 2016-07-08 18:25
Yes that's what I thought too! @hardmath123

**Comment by CosmicWebServices** [comment] 2016-07-13 20:57
yeah I noticed this

**Comment by joker314** [comment] 2016-07-13 22:41
Looks like an easy fix, you use `.push()` when you should use `.unshift()`. I couldn't find the code and therefore couldn't make a PR, but the correction should be made on line 46 of backpck.js The amended line should look like this: `parsed.unshift(obj);`
Good luck!

**Comment by tjvr** [comment] 2016-07-14 21:53
Duplicate of #161.

**Closed** 2017-02-05 13:08 UTC
Labels: discuss, forums
